# Generated by Django 4.1.3 on 2023-02-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=1, max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='fname',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='contact',
            name='lname',
            field=models.CharField(default=1, max_length=3),
        ),
        migrations.AddField(
            model_name='contact',
            name='msg',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
